deterministic: false
seed: 100
trainset_path: /home/arman/data/fwedu_10BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/train
validset_path: /home/arman/data/fwedu_10BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/valid
vocab_size: 50280
seq_len: 1024
sampler: sequential
sampler_seed: null
num_workers: 4
eval: true
eval_every_steps: 1000
model: transformer
d_model: 768
mlp_class: glu
expand: 8/3
n_layers: 12
n_heads: 12
rms_norm: true
tie_embeddings: false
torch_compile: true
steps_budget: 6100
micro_batch_size: 16
grad_accumulation_steps: 32
dtype: bfloat16
weight_decay: 0.0
beta1: 0.9
beta2: 0.95
grad_clip: null
scheduler: wsd
warmup_steps: 0
cooldown_steps: 0.25
lr_start: 1.0e-05
lr_end: 1.0e-05
lr_end_pct: null
log_every_steps: 50
print_progress: true
use_wandb: true
wandb_project: scion_sweep_160m
wandb_dir: ./logs/wandb
out_dir: ./exps_160m/experiments
over_write: true
resume: false
resume_step: null
resume_exp_name: null
save_last_checkpoint: true
save_intermediate_checkpoints: false
save_every_steps: null
optim: ngnmdv1
lr:
- 1.0e-05
- 3.0e-05
- 0.0001
- 0.0003
- 0.001
- 0.003
- 0.01
- 0.03
wandb_run_name: ngnmdv1
exp_name: ngnmdv1
