weight_decay: 0.0
beta1: 0.9
optim: scion
scion_norm_steps: 5
scion_momentum: 0.1
matrix_scale: 4.0
embed_tokens_scale: 64.0
lm_head_scale: 4096
oned_params_scale: 8
scion_ngn: global
scion_form: constrained
scion_cap: hm
scion_unconstrained: false
matrix_polyak_mult: 3.0e-02
oned_polyak_mult: 3.0e-02
embed_polyak_mult: 3.0e-02
lm_head_polyak_mult: 3.0e-02
exp_name: gngn_alpha_3e-2
wandb_run_name: gngn_alpha_3e-2
wandb_project: scion_410m_quarter_chinchilla
steps_budget: 3920
divergence_threshold: 10.0
out_dir: ./exps_410m/experiments
lr:
- 1.0e-5
- 1.0e-4
- 1.0e-3
- 1.0e-2
- 1.0e-1
- 1.0
