deterministic: false
seed: 100
trainset_path: /home/arman/data/fwedu_10BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/train
validset_path: /home/arman/data/fwedu_10BT/tokenized_EleutherAI_gpt-neox-20b/ctx_2048/valid
vocab_size: 50280
seq_len: 1024
sampler: sequential
sampler_seed: null
num_workers: 4
eval: true
eval_every_steps: 500
model: transformer
d_model: 512
mlp_class: glu
expand: 8/3
n_layers: 6
n_heads: 8
rms_norm: true
tie_embeddings: false
torch_compile: true
steps_budget: 5500
micro_batch_size: 16
grad_accumulation_steps: 16
dtype: bfloat16
weight_decay: 0.1
beta1: 0.95
beta2: 0.95
grad_clip: null
scheduler: wsd
warmup_steps: 0
cooldown_steps: 0.25
lr_start: 1.0e-05
lr_end: 1.0e-05
lr_end_pct: null
log_every_steps: 50
print_progress: true
use_wandb: true
wandb_project: scion_sweep
wandb_dir: ./logs/wandb
out_dir: ./experiments
over_write: true
resume: false
resume_step: null
resume_exp_name: null
save_last_checkpoint: true
save_intermediate_checkpoints: false
save_every_steps: null
optim: muonmax_momo
lr:
- 1.0e-05
- 3.0e-05
- 0.0001
- 0.0003
- 0.001
- 0.003
- 0.01
- 0.03
wandb_run_name: muonmax_momo
exp_name: muonmax_momo
muon_momentum: 0.95
muon_lr_scale: 10.0
truncate_loss: 0.0
stale_nuc: true
